[package]
name = "rust-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
raw-window-handle = "0.5.2"
image = { version = "0.23.12", features = ["jpeg"], default-features = false }
winit = "0.27"
wgpu = "0.16.1"
lazy_static = "1.4.0"
